apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: bootcamp1
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1
    kind: Deployment
    name: bootcamp1
  minReplicas: 3
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 60